name: Release

on:
  issues:
    types:
      - opened

jobs:
  check-release:
    name: Check if actor is eligible
    runs-on: ubuntu-latest
    outputs:
      comment-id: ${{ steps.check-maintainer-role.outputs.comment-id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check actor's permissions
        id: check-maintainer-role
        uses: ./.github/actions/check-maintainer-role
        with:
          success: Release issue noticed. Build triggered
          failure: You can't trigger a release
          label: kind/release
          token: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Test
    needs: check-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        id: test
        uses: ./.github/actions/test

      - name: Update comment
        uses: peter-evans/create-or-update-comment@v3
        if: ${{ always() }}
        id: comment
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-id: ${{ needs.check-release.outputs.comment-id }}
          body: ${{ steps.test.outcome == 'success' && '🔍 Tests passed' || '👎 Tests failed' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-build:
    name: Build
    needs: check-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        id: build
        uses: ./.github/actions/build

      - name: Update comment
        uses: peter-evans/create-or-update-comment@v3
        if: ${{ always() }}
        id: comment
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-id: ${{ needs.check-release.outputs.comment-id }}
          body: ${{ steps.build.outcome == 'success' && '🏗️ All packages are buildable' || '💣 Failed to build all packages' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release
    needs:
      - test
      - check-release
      - check-build
    runs-on: ubuntu-latest
    outputs:
      tag: v${{ steps.semantic.outputs.new_release_version }}
    steps:
      - name: Update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-id: ${{ needs.check-release.outputs.comment-id}}
          body: |
            📦 Releasing to Github and NPM

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build all packages
        uses: ./.github/actions/build

      - name: Release via semantic-release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Update comment
        uses: peter-evans/create-or-update-comment@v3
        if: ${{ steps.semantic.outputs.new_release_published != 'true' }}
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-id: ${{ needs.check-release.outputs.comment-id }}
          body: |
            ⛔ Semantic release determined that no release is needed, closing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Close issue
        uses: peter-evans/close-issue@v2
        if: ${{ steps.semantic.outputs.new_release_published != 'true' }}
        with:
          issue-number: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Exit on failure
        if: ${{ steps.semantic.outputs.new_release_published != 'true' }}
        run: exit 1

      - name: Update comment
        uses: peter-evans/create-or-update-comment@v3
        if: ${{ steps.semantic.outputs.new_release_published == 'true' }}
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-id: ${{ needs.check-release.outputs.comment-id }}
          body: |
            🎉 Released!
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
